sonar.projectKey=tfg-financial-scraper
sonar.projectName=TFG Financial Scraper
sonar.projectVersion=0.1.0

sonar.sources=.
sonar.exclusions=data/**,resources/**,**/__pycache__/**,**/*.pyc

sonar.python.version=3.12
